name: 型チェック

on:
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: 依存パッケージのインストール
        run: npm ci
        
      - name: TypeScript型チェック
        run: npm run type-check  # または tsc --noEmit
